#!/usr/bin/env zsh

taps=(
    caskroom/cask
)

packages=(
    ag
    aspell
    cmus
    git
    gnupg
    gpg-agent
    graphviz
    heroku
    htop-osx
    httpie
    imagemagick
    node
    openssl
    postgresql
    python
    python3
    reattach-to-user-namespace
    rsync
    tmux
    tree
    vim
    wget
    xz
    zsh
)

cask_packages=(
    arq
    dropbox
    firefox
    iterm2
    the-unarchiver
    virtualbox
    xquartz
)

function log() {
    echo $* > /dev/stderr
}

log "brew update"
brew update

log "brew upgrade"
brew upgrade

log "tapping"
for name in $taps
do
    log "brew tap ${name}"
    brew tap $name
done

log "installing"
for name_and_args in $packages
do
    log "brew install ${=name_and_args}"
    brew install "${=name_and_args}"
done

for name_and_args in $cask_packages
do
    log "brew cask install ${=name_and_args}"
    brew cask install "${=name_and_args}"
done

log "brew cleanup"
brew cleanup
