# personal
[[workspace]]
path = "$HOME/projects/personal"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@pingo.thermokar.st"
origin.name = "pingo"
repos = [
  "cs685",
  "dot_ssh",
  "dotfiles",
  "elixir-class",
  "gitolite-admin",
  "gpx-web-utils",
  "gwar",
  "notes",
  "pingo",
]
remotes = []

# personal-dokku
[[workspace]]
path = "$HOME/projects/personal"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@pingo.thermokar.st"
origin.name = "pingo"
repos = [
  "akdillon",
  "planner",
  "thermokar.st",
  "zettel",
]
remotes = [
  { name = "dokku", base_addr = "ssh://dokku@pingo.thermokar.st" },
]

# mds
[[workspace]]
path = "$HOME/projects/mds"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@pingo.thermokar.st"
origin.name = "pingo"
repos = [
  "arctic_hibernators_schema",
  "bactdb",
  "bactdb_data",
  "ccdb-api",
  "ccdb-old",
  "ccdb-web",
  "drf_ember_pagination",
  "hibernators",
  "hibernators-web",
  "hymenobacterdotinfo",
]
remotes = []

# github-thermokarst-personal
[[workspace]]
path = "$HOME/projects/personal"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@github.com/thermokarst"
origin.name = "thermokarst"
repos = [
  "thermokarst",
]
remotes = []

# github-thermokarst-qiime2
[[workspace]]
path = "$HOME/projects/qiime2"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@github.com/thermokarst"
origin.name = "thermokarst"
repos = [
  "q2-no-op",
  "workflows-playground",
]
remotes = []

# github-thermokarst-forks-qiime2
[[workspace]]
path = "$HOME/projects/qiime2"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@github.com/qiime2"
origin.name = "qiime2"
repos = [
  "Keemei",
  "action-library-packaging",
  "busywork",
  "conda-channel-resource",
  "data302",
  "dev-docs",
  "docs",
  "environment-files",
  "library",
  "logos",
  "package-integration",
  "paper1",
  "paper2",
  "q2-alignment",
  "q2-composition",
  "q2-cutadapt",
  "q2-dada2",
  "q2-deblur",
  "q2-demux",
  "q2-diversity",
  "q2-diversity-lib",
  "q2-emperor",
  "q2-feature-classifier",
  "q2-feature-table",
  "q2-fragment-insertion",
  "q2-gneiss",
  "q2-longitudinal",
  "q2-metadata",
  "q2-mystery-stew",
  "q2-phylogeny",
  "q2-quality-control",
  "q2-quality-filter",
  "q2-sample-classifier",
  "q2-taxa",
  "q2-types",
  "q2-vsearch",
  "q2cli",
  "q2cwl",
  "q2galaxy",
  "q2lint",
  "q2studio",
  "q2templates",
  "q2view",
  "qiime2",
  "qiime2.github.io",
  "sphinx-ext-qiime2",
  "sphinx-qiime2-theme",
  "static-site-infrastructure",
  "template-repo",
  "view.qiime2.org",
  "vm-playbooks",
  "workshop-playbooks",
  "workshops",
]
remotes = [
  { name = "ChrisKeefe", base_addr = "ssh://git@github.com/ChrisKeefe" },
  { name = "Keegan-Evans", base_addr = "ssh://git@github.com/Keegan-Evans" },
  { name = "Oddant1", base_addr = "ssh://git@github.com/Oddant1" },
  { name = "cherman2", base_addr = "ssh://git@github.com/cherman2" },
  { name = "ebolyen", base_addr = "ssh://git@github.com/ebolyen" },
  { name = "gregcaporaso", base_addr = "ssh://git@github.com/gregcaporaso" },
  { name = "lizgehret", base_addr = "ssh://git@github.com/lizgehret" },
  { name = "nbokulich", base_addr = "ssh://git@github.com/nbokulich" },
  { name = "thermokarst-forks", base_addr = "ssh://git@github.com/thermokarst-forks" },
]

# github-thermokarst-forks-caporaso-lab
[[workspace]]
path = "$HOME/projects/qiime2"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@github.com/caporaso-lab"
origin.name = "caporaso-lab"
repos = [
  "caporaso-lab.github.io",
  "code-of-conduct",
  "genome-sampler",
  "pretrained-feature-classifiers",
  "q2-phylogenomics",
]
remotes = [
  { name = "ebolyen", base_addr = "ssh://git@github.com/ebolyen" },
  { name = "gregcaporaso", base_addr = "ssh://git@github.com/gregcaporaso" },
  { name = "thermokarst-forks", base_addr = "ssh://git@github.com/thermokarst-forks" },
]

# github-thermokarst-forks-biocore
[[workspace]]
path = "$HOME/projects/qiime2"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@github.com/biocore"
origin.name = "biocore"
repos = [
  "deblur",
  "emperor",
  "gneiss",
  "scikit-bio",
]
remotes = [
  { name = "ebolyen", base_addr = "ssh://git@github.com/ebolyen" },
  { name = "thermokarst-forks", base_addr = "ssh://git@github.com/thermokarst-forks" },
]

# github-thermokarst-forks-bokulich-lab
[[workspace]]
path = "$HOME/projects/qiime2"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@github.com/bokulich-lab"
origin.name = "bokulich-lab"
repos = [
  "RESCRIPt",
]
remotes = [
  { name = "nbokulich", base_addr = "ssh://git@github.com/nbokulich" },
  { name = "thermokarst-forks", base_addr = "ssh://git@github.com/thermokarst-forks" },
]

# github-thermokarst-forks-conda-forge
[[workspace]]
path = "$HOME/projects/qiime2"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@github.com/conda-forge"
origin.name = "conda-forge"
repos = [
  "biom-format-feedstock",
  "ijson-feedstock",
  "scikit-bio-feedstock",
]
remotes = [
  { name = "thermokarst-forks", base_addr = "ssh://git@github.com/thermokarst-forks" },
]

# github-gregcaporaso
[[workspace]]
path = "$HOME/projects/qiime2"
ssh_key_path = "$HOME/.ssh/id_ecdsa"
origin.base_addr = "ssh://git@github.com/gregcaporaso"
origin.name = "gregcaporaso"
repos = [
  "caporaso-lab-secrets",
  "qiime2-meta-figures",
]
remotes = []
