theme = "catppuccin_mocha"

[editor]
true-color = true
insert-final-newline = false
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.file-picker]
hidden = false

[keys.normal]
C-r = ":reload-all"
C-y = ":sh zellij run -c -f -x 5% -y 5% --width 90% --height 90% -- bash ~/.config/helix/yazi-picker.sh open"

[keys.normal.C-m]
t = ":sh run_test_under_cursor"
