theme = "catppuccin_mocha"

[editor]
true-color = true
insert-final-newline = false

[editor.file-picker]
hidden = false

[keys.normal]
C-r = ":reload-all"

[keys.normal.C-m]
t = ":sh run_test_under_cursor"
