[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.zk]
command = "zk"
args = ["lsp"]

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown"]
roots = [".zk"]
language-servers = ["zk"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}
environment = { "PYENV_VERSION" = "pyright" }

[[language]]
name = "python"
language-servers = ["pyright"]
