[user]
name = "Matthew Ryan Dillon"
email = "matthewrdillon@gmail.com"

[git]
push-branch-prefix = "thermokarst/jj-"

[revsets]
log = "@ | bases | branches | curbranch::@ | @::nextbranch | downstream(@, branchesandheads)"

[revset-aliases]
'bases' = 'main'
'downstream(x,y)' = '(x::y) & y'
'branches' = 'downstream(trunk(), branches()) & mine()'
'branchesandheads' = 'branches | (heads(trunk()::) & mine())'
'curbranch' = 'latest(branches::@- & branches)'
'nextbranch' = 'roots(@:: & branchesandheads)'
'stack' = 'bases..@'

[ui]
default-command = ["log"]
pager = "delta"

[ui.diff]
format = "git"

[merge-tools.delta]
diff-args = [
  "--color-only",
  "--features", "chameleon",
  "--navigate",
  "--dark",
  "--side-by-side",
  "--true-color", "always",
  "--syntax-theme", "base16",
  "$left", "$right",
]
