[notebook]
dir = "~/notebook"

[note]
language = "en"
default-title = "untitled"
filename = "{{format-date now 'timestamp'}}-{{id}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"

[group.journal]
paths = ["journal/daily"]

[group.journal.note]
filename = "{{format-date now}}"
template = "daily.md"

[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[alias]
save = 'jj desc -m "$*" && jj bookmark set main -r @ && jj new'
sync = 'jj git fetch && jj git push'
log = 'jj log -r ".."'
diff = 'jj diff'
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal/daily"'

[tool]
editor = "hx"
fzf-preview = "bat -p --color always {-1}"
