# Matthew Dillon
# matthewrdillon@gmail.com

# add unique paths from PATH to PATH_SAVE and replace PATH with PATH_SAVE
if [ -n "$PATH_SAVE" ]; then
  PATH_SAVE=:$PATH_SAVE:;
  PATH=$PATH:
  while [ -n "$PATH" ]; do
   x=${PATH%%:*}
   case $PATH_SAVE in
     *:$x:*) ;;
     *) PATH_SAVE=$PATH_SAVE$x: ;;
   esac
   PATH=${PATH#*:}
  done
  PATH=${PATH_SAVE:1:-1}
  unset PATH_SAVE x
  export PATH
fi
