#
# Defines environment variables.
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

#
# Paths
#

# shortcuts to projects
export CDPATH="$CDPATH:$HOME/src/biocore"
export CDPATH="$CDPATH:$HOME/src/caporaso-lab"
export CDPATH="$CDPATH:$HOME/src/gregcaporaso"
export CDPATH="$CDPATH:$HOME/src/qiime2"
export CDPATH="$CDPATH:$HOME/src/thermokarst"
export CDPATH="$CDPATH:."

# miniconda
export PATH="/opt/miniconda3/bin:$PATH"

# macports
export PATH="/opt/local/bin:$PATH"
export PATH="/opt/local/sbin:$PATH"

# golang
export GOROOT=/opt/go
export PATH="$GOROOT/bin:$PATH"

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
cdpath=(
  $cdpath
)

# Set the list of directories that Zsh searches for programs.
path=(
  $path
  /usr/local/{bin,sbin}
)

export -U PATH
